// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class CustomLevelPublishModuleBindings
    {
        readonly ICloudCodeService k_Service;

        /// <summary>
        /// 使用默认的 Cloud Code Service 实例创建自定义关卡发布模块绑定。
        /// </summary>
        public CustomLevelPublishModuleBindings() : this(CloudCodeService.Instance) { }

        /// <summary>
        /// 使用指定的 Cloud Code Service 实例创建自定义关卡发布模块绑定。
        /// </summary>
        /// <param name="service">用于调用 Unity Cloud Code Module 的服务实例。</param>
        public CustomLevelPublishModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        /// <summary>
        /// 将当前玩家创建的自定义关卡发布到云端公开关卡池。
        /// </summary>
        /// <param name="levelInfo">需要上传的自定义关卡数据，包括关卡标题、尺寸、方块和颜色信息。</param>
        /// <param name="displayName">发布者显示名称，用于其他玩家浏览公开关卡时展示。</param>
        /// <param name="clientVersion">当前客户端版本号，用于服务端记录上传来源版本。</param>
        /// <returns>发布结果，包含是否成功、公开关卡 ID、发布状态和云端关卡记录。</returns>
        public async Task<MagicPixelCustomLevelPublish.CustomLevelPublishResult> PublishCustomLevel(MagicPixelCustomLevelPublish.CustomLevelUploadRequest levelInfo, string displayName, string clientVersion)
        {
            return await k_Service.CallModuleEndpointAsync<MagicPixelCustomLevelPublish.CustomLevelPublishResult>(
                "MagicPixelCustomLevelPublish",
                "PublishCustomLevel",
                new Dictionary<string, object>()
                {
                    {"levelInfo", levelInfo},
                    {"displayName", displayName},
                    {"clientVersion", clientVersion},
                });
        }

        /// <summary>
        /// 分页获取云端已公开发布的自定义关卡列表。
        /// </summary>
        /// <param name="sortType">排序方式，例如按最新发布或热门程度排序。</param>
        /// <param name="pageSize">本次请求的关卡数量，服务端会限制最大分页数量。</param>
        /// <param name="cursor">分页游标，首次请求可传空字符串或 null。</param>
        /// <returns>公开关卡列表结果，包含当前页数据和下一页游标。</returns>
        public async Task<MagicPixelCustomLevelPublish.CustomLevelListResult> GetPublishedCustomLevels(string sortType, int pageSize, string cursor)
        {
            return await k_Service.CallModuleEndpointAsync<MagicPixelCustomLevelPublish.CustomLevelListResult>(
                "MagicPixelCustomLevelPublish",
                "GetPublishedCustomLevels",
                new Dictionary<string, object>()
                {
                    {"sortType", sortType},
                    {"pageSize", pageSize},
                    {"cursor", cursor},
                });
        }

        /// <summary>
        /// 根据公开关卡 ID 获取单个已发布自定义关卡的详情。
        /// </summary>
        /// <param name="publicLevelId">云端公开关卡 ID。</param>
        /// <returns>公开关卡详情记录。</returns>
        public async Task<MagicPixelCustomLevelPublish.CustomLevelPublicRecord> GetPublishedCustomLevel(string publicLevelId)
        {
            return await k_Service.CallModuleEndpointAsync<MagicPixelCustomLevelPublish.CustomLevelPublicRecord>(
                "MagicPixelCustomLevelPublish",
                "GetPublishedCustomLevel",
                new Dictionary<string, object>()
                {
                    {"publicLevelId", publicLevelId},
                });
        }

        /// <summary>
        /// 记录一次玩家体验公开关卡的行为，并返回该关卡的最新详情。
        /// </summary>
        /// <param name="publicLevelId">云端公开关卡 ID。</param>
        /// <returns>更新体验次数后的公开关卡详情记录。</returns>
        public async Task<MagicPixelCustomLevelPublish.CustomLevelPublicRecord> PlayPublishedCustomLevel(string publicLevelId)
        {
            return await k_Service.CallModuleEndpointAsync<MagicPixelCustomLevelPublish.CustomLevelPublicRecord>(
                "MagicPixelCustomLevelPublish",
                "PlayPublishedCustomLevel",
                new Dictionary<string, object>()
                {
                    {"publicLevelId", publicLevelId},
                });
        }

        /// <summary>
        /// 对指定公开关卡执行点赞操作。
        /// </summary>
        /// <param name="publicLevelId">云端公开关卡 ID。</param>
        /// <returns>点赞结果，包含是否成功、当前点赞状态、点赞数量和最新关卡记录。</returns>
        public async Task<MagicPixelCustomLevelPublish.CustomLevelLikeResult> LikePublishedCustomLevel(string publicLevelId)
        {
            return await k_Service.CallModuleEndpointAsync<MagicPixelCustomLevelPublish.CustomLevelLikeResult>(
                "MagicPixelCustomLevelPublish",
                "LikePublishedCustomLevel",
                new Dictionary<string, object>()
                {
                    {"publicLevelId", publicLevelId},
                });
        }

        /// <summary>
        /// 撤销当前玩家自己发布的公开自定义关卡。
        /// </summary>
        /// <param name="publicLevelId">需要撤销的云端公开关卡 ID。</param>
        /// <returns>撤销结果，包含是否成功、公开关卡 ID 和撤销后的状态。</returns>
        public async Task<MagicPixelCustomLevelPublish.CustomLevelRevokeResult> RevokePublishedCustomLevel(string publicLevelId)
        {
            return await k_Service.CallModuleEndpointAsync<MagicPixelCustomLevelPublish.CustomLevelRevokeResult>(
                "MagicPixelCustomLevelPublish",
                "RevokePublishedCustomLevel",
                new Dictionary<string, object>()
                {
                    {"publicLevelId", publicLevelId},
                });
        }
    }
}
