// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.MagicPixelCustomLevelPublish
{
    public partial class CustomLevelRevokeResult
    {
        public bool success;
        public string publicLevelId;
        public int status;
        public string message;

        [Preserve]
        public CustomLevelRevokeResult ()
        {
        }
    }
}