// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.MagicPixelCustomLevelPublish
{
    public partial class CustomLevelPublicRecord
    {
        public int schemaVersion;
        public string publicLevelId;
        public string sourceLocalLevelId;
        public string ownerPlayerId;
        public string ownerDisplayName;
        public string title;
        public int size;
        public List<int> block;
        public List<CustomLevelColorInfo> colors;
        public int likeCount;
        public int playCount;
        public int status;
        public bool likedByCurrentPlayer;
        public long createdAtUtcTicks;
        public long updatedAtUtcTicks;
        public string clientVersion;
        public string unityEnvironment;
        public List<string> likedPlayerIds;

        [Preserve]
        public CustomLevelPublicRecord ()
        {
        }
    }
}