// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.MagicPixelCustomLevelPublish
{
    public partial class CustomLevelLikeResult
    {
        public bool success;
        public bool liked;
        public int likeCount;
        public string message;
        public CustomLevelPublicRecord record;

        [Preserve]
        public CustomLevelLikeResult ()
        {
        }
    }
}