// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.MagicPixelCustomLevelPublish
{
    public partial class CustomLevelColorInfo
    {
        public int index;
        public string color;

        [Preserve]
        public CustomLevelColorInfo ()
        {
        }
    }
}