// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.MagicPixelCustomLevelPublish
{
    public partial class CustomLevelUploadRequest
    {
        public string sourceLocalLevelId;
        public string title;
        public int size;
        public List<int> block;
        public List<CustomLevelColorInfo> colors;

        [Preserve]
        public CustomLevelUploadRequest ()
        {
        }
    }
}