// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.MagicPixelCustomLevelPublish
{
    public partial class CustomLevelListResult
    {
        public bool success;
        public List<CustomLevelPublicRecord> items;
        public string nextCursor;
        public string message;

        [Preserve]
        public CustomLevelListResult ()
        {
        }
    }
}